"""Initial Migration

Revision ID: fc95e807ae17
Revises: 07e883028ac7
Create Date: 2023-01-27 01:10:04.470580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc95e807ae17'
down_revision = '07e883028ac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tbl_users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_users', type_='unique')
    op.drop_column('tbl_users', 'username')
    # ### end Alembic commands ###
